- http.go
- http_test.go
- tcp_test.go
Fix bug in default status codes accepted by http.
Allow for how redirect errors are handled.
@fabxc
> Add unittests for http and tcp.

- Dockerfile
- README.md
The other official tools all seem to have a dockerfile (and be on the hub), and we use this capability (along with docker-compose) to deploy prometheus.
This adds the Dockerfile and basic documentation in a way which seems consistent with the other `prom/` projects.
> Added basic Dockerfile support & documentation

- README.md
- http.go
- http_test.go
- main.go
Another try. This CL makes https://github.com/prometheus/blackbox_exporter/pull/35 obsolete and adds a more general headers map as discussed before.
> configureable http headers for the http probe

- README.md
This exporter does not need to be run as root to use the ICMP module, we should probably avoid implying as such.
> Add notes for privileges necessary for ICMP module

- README.md
- dns.go
- dns_test.go
- http.go
- icmp.go
- main.go
- tcp.go
- tcp_test.go
Introduce protocol field for every module which can be used to force
probe to IPv4 (tcp4 or icmp4) or IPv6 (tcp6 or icmp6). Default for tcp
and http modules is current behaviour - let stack decide. Default for
icmp is also current behaviour - IPv4.
> IPv6 support for all modules

- http.go
The url parsing is treating URLs without schemes
as paths rather than hosts.
Fixes #69
> Add scheme before attempting URL parsing.

- icmp.go
> Fix 'socker' typo

- icmp.go
Panic:
ERRO[0003] Error resolving address bbc.co.uk: no suitable address found
source="icmp.go:81"
2017/01/27 16:40:42 http: panic serving 127.0.0.1:57487: runtime error:
invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc420086700)
/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x84e600, 0xc4200100e0)
/usr/local/go/src/runtime/panic.go:458 +0x243
main.probeICMP(0xc420017752, 0x9, 0xabc7c0, 0xc4200f0d00, 0xc4200f64e8,
0x4, 0x12a05f200, 0x0, 0x0, 0x0, ...)
/home/luke/git/blackbox_exporter/icmp.go:84 +0x1fc
main.probeHandler(0xabc7c0, 0xc4200f0d00, 0xc42001c1e0, 0xc420030090)
/home/luke/git/blackbox_exporter/main.go:130 +0x218
main.main.func1(0xabc7c0, 0xc4200f0d00, 0xc42001c1e0)
/home/luke/git/blackbox_exporter/main.go:170 …
> Fix panic in ICMP on DNS lookup failure

- icmp.go
measures how long the DNS lookup takes and adds `prober_dns_lookup_time_seconds` as discussed in #60.
My first pull request ever, please let me know if I did something wrong in the process!
> add prober_dns_lookup_time_seconds metric to solve #60

- README.md
To reduce confusion about how to use http probes, simplify the `http_2xx` probe example.
* Make the example use full URLs for targets.
* Remove relabel config params that are defaults.
Closes: https://github.com/prometheus/blackbox_exporter/issues/159
> Improve example prometheus.yml config

- http.go
This makes the gauge show up in the probe output when a TLS endpoint is
probed.
Signed-off-by: Kai Blin <kblin@biosustain.dtu.dk>
> Register probeSSLEarliestCertExpiryGauge

- README.md
The former links resulted to errors from github.
> Fix broken Links in README

- CONFIGURATION.md
- config.go
- example.yml
- http.go
- http_test.go
Implements #162.
Exposes HTTP version via `probe_http_version` gauge and probes can now have set valid HTTP versions that will fail if not met.
> Expose HTTP version of probe

- example.yml
Hi here, this PR fixes this issue with default config. « Error parsing config file: unknown fields in dns probe: protocol »
Refs: https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md#dns_probe
> doc: Rename protocol to transport_protocol

- main.go
- vendor/github.com/prometheus/common/log/log.go
- vendor/vendor.json
The logging flags are no longer automatically set, which was missed in the kingpin conversion.
> Fix logging flags

- main.go
Some minutes ago, my monitoring system notified me about problems with the blackbox_exporter which updates automatically on new releases. It seems that in version 0.8.0, the flag for the config file was accidentally renamed to `--config-flag`.
> Fix wrong config flag name in 0.8.0 (--config-flag=..)

- CONFIGURATION.md
- config/config.go
- config/testdata/blackbox-good.yml
- example.yml
- prober/tcp.go
- prober/tcp_test.go
- prober/utils_test.go
This change adds tls-upgrade feature for tcp-probing also known as STARTTLS. This allows probing protocols like SMTP, IMAP, POP3 (also for certificate expiry) with the tcp-prober by adding a starttls directive to the query_response configuration.
> add tls-upgrade for tcp-prober (STARTTLS)

- example.yml
- prober/tcp.go
- prober/tcp_test.go
- prober/utils_test.go
Because dialTCP manually resolves name to IP, the
actual tls.DialWithDialer call cannot deduce the name
from the target. This changes puts the "lost" name
into tlsConfig to fix certficate name verification.
Tests are also added which fail without and succeed
with this change.
This fixes #225
> [prober/tcp] get servername for TLS from target

- prober/http.go
- prober/http_test.go
> Set TLS servername or target's host for HTTP probe.

- CONFIGURATION.md
- config/config.go
- prober/icmp.go
@RichiH wanted to add the payload size and DF-bit to be configurable in the ICMP prober. While I had fun implementing this, I would like to know if this is okay before I put in more effort.
cc/ @brian-brazil @SuperQ
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/prometheus/blackbox_exporter/240)
> Advanced ICMP options

- .travis.yml
- circle.yml
- prober/utils.go
Wrap the DNS lookup time `defer` in an anonymous function to avoid arguments being evaluated early.
Closes: https://github.com/prometheus/blackbox_exporter/issues/253
> Wrap DNS lookup metric time defer

- prober/dns.go
- prober/http.go
- prober/http_test.go
- prober/icmp.go
- prober/tcp.go
- prober/utils.go
Hi,
this is pretty much the prober I use for the latency.at exporters. I've added it as a new module here although in my exporters I replaced the http module which might make sense, given that it basically only adds one new metric.
Beside that I still need refactor and move over some tests. But wanted to get feedback early. I expected especially the redirect stuff to something to discuss.
> Add httptrace based prober

- main.go
- prober/http.go
- prober/tcp.go
Note that one out of the three modified getEarliestCertExpiry() lines was doing integer division anyway, and was thus futile. The other two were at least converting the UnixNano() to float64 before dividing it by 1e9, but I'm not sure if anyone _really_ cares about nanoseconds on a TLS cert expiry. However, if they do, I'd then still recommend using a `float64(time.Second)` constant for pedantry's sake.
> Use net/http, time package constants

- README.md
Improve the clarity of how to use the relabel config to adjust the
blackbox exporter target.
> Improve relabel config documentation

- prober/http.go
This got broken as part of introducing the Prometheus client library for
metrics exposure in 7abdf0570d44cc8dbd258987e9d3353af1d6126e.
> Fix HTTP content length metric name

- main.go
Add posibility to check config and exit, usefull with CI that check config repo before merging to master
> Add config validation option

- history.go
- main.go
This change replaces the hardcoded limit on the number of elements stored in the log history with a configurable value that can be set as a runtime argument. The the old value of 100 elements will be use by default either when the argument is left off or the argument is out of range (less than 1).
The driving use case for this is when there are over 100 endpoints queried, some of them will be removed almost immediately from the logs.
> Make the history limit a configurable flag

- config/config.go
- config/config_test.go
- vendor/gopkg.in/yaml.v2/NOTICE
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/apic.go
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/go.mod
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/sorter.go
- vendor/gopkg.in/yaml.v2/writerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
- vendor/vendor.json
As a followup from prometheus/prometheus#4033 and prometheus/common/pull/127, I added strict yaml unmarshalling by updating the yaml vendor package and removing unnecessary checks and data structures.
I avoided code refactoring on the yaml Unmarshaler implementations inside `config/config.go` for this PR, in order to keep it simple. Please let me know if I should change it.
> Implement strict yaml unmarshalling.

- prober/icmp.go
Changed code to unify the IPv6 and IPv4 ICMP usage, and also how the source IP is used (listen on the source IP instead of defining it on the packet). Tested on Windows for both IPv4 and IPv6, with and without explicit source IP.
Not tested DF flag and *nix in general.
> For ICMP, only use RawConn for the Don't Fagment case

- .travis.yml
- prober/icmp.go
Add a gauge to measure various parts of the ICMP probe.
Fixes: https://github.com/prometheus/blackbox_exporter/issues/315
> Add ICMP duration metrics

- .travis.yml
- prober/utils_test.go
```
$ make
>> checking code style
! gofmt -d $(find . -path ./vendor -prune -o -name '*.go' -print) | grep '^'
diff -u ./prober/utils_test.go.orig ./prober/utils_test.go
--- ./prober/utils_test.go.orig	2018-09-25 11:52:34.000000000 -0700
+++ ./prober/utils_test.go	2018-09-25 11:52:34.000000000 -0700
@@ -43,7 +43,7 @@
publickey := &privatekey.PublicKey
cert := x509.Certificate{
-		IsCA: true,
+		IsCA:                  true,
BasicConstraintsValid: true,
SubjectKeyId:          []byte{1},
SerialNumber:          big.NewInt(1),
make: *** [style] Error 1
```
> Fix broken build because of go fmt issue

- prober/http.go
Withot this change `transfer` time is near zero, because `trace.end` time is clocked when response body is available, not when it's read.
cc @discordianfish
> Account response read time for http prober

- prober/http.go
This feature returns a `probe_http_last_modified` metric with the content of the Last-Modified HTTP response header, if it is set by the server.
That feature would be nice for (blackbox) monitoring, if a service that should regularly update a website, is working or not.
-------
P.S.: someone encountered me to the fact, that registering the gauges shouldn't be repeated in each probe, but only at initializing the exporter. This isn't part of this PR.
https://github.com/prometheus/blackbox_exporter/blob/22be14377a74e81e6c4c77a5577c14f944aa2277/prober/http.go#L181-L187
> Implemented Last-Modified HTTP header metric

- prober/icmp.go
This should help preventing issues with some network devices that have
trouble NATing ICMP packets with the same ID and sequence nubmer but a
different source IP address.
Currently, this can happen if the blackbox_exporter runs in a container
(the ID is set to the PID, which is typically 1 in a container), and
serveral blackbox_exporters are restarted at the same time (the sequence
numbers are reset to zero and stay in sync).
This commit sets the ICMP echo ID to a random value if the PID is 1, and
initializes the sequence number at a random offset.
See #411 for details.
> Initialize ICMP echo ID and sequence to random values

- blackbox.yml
The null then overrides the default config. Avoid this
in the example config file.
> Empty in YAML means null.

- config/config.go
- config/config_test.go
- main_test.go
- prober/prober.go
- prober/utils.go
- prober/utils_test.go
This license is copied out of the main.go file.
Signed-off-by: silentpete <peter.gallerani@gmail.com>
> add license information to missing Go files (resolves #448)

- README.md
Separating build and run instructions, so users can just download the released software, or opt for the public docker container the project is already maintaining
> README update so run (without build) instructions are clear

- main.go
Use Alertmanager main.go as an example to exit 0 when blackbox_exporter service receives SIGTERM.
Signed-off-by: silentpete <peter.gallerani@gmail.com>
> update main.go to allow for docker stop, exit 0 (resolves #447)

- history.go
- main.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- main.go
- main_test.go
The current default of 10s is problematic when testing slower probes
from a browser. Cancellation will still work as a fallback,
including for older Prometheus servers that don't send the timeout
header, so there shouldn't be a big buildup of ongoing probes.
Fixes #259
> Bump default timeout to 2m

- main.go
> Use HTTP request's context, so cancellation works.

- prober/dns_test.go
- prober/tcp_test.go
IIUC e4ffafac0b71edc4c8cf75859755032a42258f7c modified/removed the `Protocol` option for TCP and DNS probes. This introduced duplicated test cases.
> prober: remove duplicated tests

- history.go
- history_test.go
- main.go
This PR adds a new section to the history to hold onto failed probes after they expire from the main history. This allows us to check what debug logs for failed probes in environments with a high rate of successful probes.
I implemented this to be strictly additive for the sake of backwards compatibility. The Web UI has a separate section for these preserved failures.
Resolves #350
> Add separate history for expired failed probe results

- main.go
The front page contains a table of links to logs from the most recent
probes. These links were accidentally changed to absolute links in
252a878, in a form that doesn't work when using --web.external-url.
Rather than prefixing these with the external URL (if set), we return
them to being relative links, as they are meant to be (per issue #519).
Fixes #519
Signed-off-by: Chris Siebenmann <cks.git01@cs.toronto.edu>
> Change the front page links to probe logs into relative links

- prober/http.go
Partial solution for https://github.com/prometheus/blackbox_exporter/issues/337
I think this is a suitable solution for cases "we need to monitor the size of very important page and alert when it dramatically changed". I just get the size of the response body (which transparently decompressed by http.Response) and expose it.
Page with disabled compression:
```
http://localhost:9115/probe?target=example.com&module=http_2xx
probe_http_content_length 1270
probe_http_uncompressed_body_length 1270
```
Page with enabled compression:
```
http://localhost:9115/probe?target=github.com&module=http_2xx
probe_http_content_length -1
probe_http_uncompressed_body_length 134683
```
Nonexistent site:
```
http://localhost:9115/probe?target=notexistent.site&module=http_2xx
probe_http_content_length 0 …
```
> Add probe_http_uncompressed_body_length metric

- prober/http.go
- prober/http_test.go
If the redirect is to a different host, don't set ServerName.
Fixes #237.
@discordianfish @SuperQ
> Better handling of HTTP redirects.

- prober/http.go
- prober/tcp.go
- prober/tcp_test.go
- prober/tls.go
- prober/utils_test.go
This PR adds the TLS version to the exported variables, or NaN when it is unknown (maybe that should be 0 instead?). All currently available TLS versions are covered. SSL3 is not, as it is not TLS and will be removed in Go 1.14 (See https://github.com/golang/go/issues/32716).
> Export TLS version

- prober/dns_test.go
- prober/tcp_test.go
- prober/utils.go
- prober/utils_test.go
- fix ip protocol fallback
- before the argument `fallbackIPProtocol` in `chooseProtocol()` (`prober/utils.go`) was never used
- correct / get default value of `IPProtocol` during testing
- `ipv4` is a wrong value, it should be `ip4` or `ip6`
-
> [BUGFIX] disable ip protocol fallback and tests

- prober/utils.go
Also add logging missing from one code path.
Fixes #546
> Fix logging of IP addresseses in resolve code.

- CONFIGURATION.md
- config/config.go
- example.yml
- prober/dns.go
- prober/dns_test.go
The current validators for the DNS probers (if_matches/if_not_matches) pass if _any_ record matches/does not match. This patch adds the opposite sense of each, so that a validation will pass if _no_ records match, or _all_ records match. This is much more useful for example with TXT records where you might want to check if a particular record is present or not without failing if any record does not match.
> Add none/all matches to DNS RRset validation

- prober/http_test.go
- prober/utils_test.go
Skip the network-dependent `TestChooseProtocol` test when testing in short mode. Also fix spelling of "dependent" elsewhere in tests.
> Skip network dependent test in short mode

- prober/utils.go
add `probe_ip_addr_hash` metrics to specify the hash of IP address
We want to detect if the IP is changed by `change(probe_ip_addr_hash[10h])`
Assume you use CDN and you want to monitoring your web server.
```
blackbox_exporter --> CDN edge server --> origin server
```
if the edge server failover, blackbox exporter returns error and the IP address will be changed.
With `probe_ip_addr_hash`, we can tell the error happen due to edge failover.
> add probe_ip_addr_hash to detect if the IP changes

- CONFIGURATION.md
- Add `password_file` field to document of http probe.
- Ref. https://github.com/prometheus/blackbox_exporter/blob/v0.16.0/vendor/github.com/prometheus/common/config/http_config.go#L43
> Add password file field to document

- example.yml
- prober/http_test.go
I spent some time trying to understand why I was getting errors like `msg="Invalid HTTP version number" version=2` while my config looked fine: `valid_http_versions: ["HTTP/1.1", "HTTP/2"]`.
Turns out that HTTP/2 is not called HTTP/2 but HTTP/2.0 in the golang HTTP client, so this fixes the example to showcase that.
> Fix the HTTP/2 example

- prober/http.go
- prober/http_test.go
- prober/tcp.go
- prober/tcp_test.go
- prober/tls.go
- prober/utils_test.go
Resolves https://github.com/prometheus/blackbox_exporter/issues/340
Based on the discussion in the issue above, this metric will help determine
when the SSL/TLS certificate expiration error actually happens on clients
like a browser that attempts to verify certificates by building one or
more chains from peer certificates.
> Add new probe_ssl_latest_verified_chain_expiry metric

- CONFIGURATION.md
- config/config.go
- config/config_test.go
- config/testdata/invalid-dns-class.yml
- config/testdata/invalid-dns-type.yml
- prober/dns.go
- prober/dns_test.go
**Context**
In some cases we might want to probe other DNS class than the INET one; for instance we could probe the server version often exposed in a `TXT CH version.bind` record.
This PR offers the ability to do so by setting `query_class` in your prober configuration, the default is `"IN"` as it was before.
**Implementation note**
Most of the code is a copy/paste/replace of the `query_type` setting; except that the `setQuestion` call has been replaced by its "[slightly more verbose, but more flexible](https://godoc.org/github.com/miekg/dns)" alternative.
> [dns] Allow to specify query Class

- prober/icmp.go
> Seed RNG to ensure different ICMP ids.

- CONFIGURATION.md
- README.md
- prober/icmp.go
This works for Linux and Darwin.
On Linux the user running the exporter needs to be a member of a group
with an ID in the range specified in the sysctl
net.ipv4.ping_group_range.
Fixes #147.
I've tested this on:
Works, able to set ID and confirmed with tcpdump the ID is the same on outgoing
packets.
Kernel always overwrites ID, e.g.:
```
ts=2020-06-16T11:53:06.722Z caller=main.go:169 module=icmp target=127.0.0.1 level=debug msg="Creating ICMP packet" seq=46268 id=17449
```
tcpdump:
```
12:53:06.722861 IP 127.0.0.1 > 127.0.0.1: ICMP echo request, id 62, seq 46268, length 36
```
The code takes this into account.
Works when:
```
sysctl -w net.ipv4.ping_group_range='0	2147483647'
```
Example log:
```
ts=2020-06-16T11:53:06.722Z caller=main.go:169 module=icmp target=127.0.0.1 level=debug …
```
> Add support for "rootless" ping

- CONFIGURATION.md
- config/config.go
- prober/dns.go
This adds a new DNS probe option `dns_over_tls` to enable DoT on DNS probes.
> Add support for DoT to DNS probes

- CONFIGURATION.md
- config/config.go
- prober/dns.go
> Add option to disable TLS certificate check in DoT

- prober/http.go
Recent versions of Go have started enforcing the usage of
brackets in URLs with literal IPv6 addresses. This change
prevents the attempt to resolve an address in the form
[address]. URL.Hostname() takes care of striping the brackets.
Signed-off-by: André Cruz <acruz@cloudflare.com>
> Deal with URLs with literal IPv6 addresses

- prober/dns.go
This change the default port of DNS-over-TLS to 853.
Fix https://github.com/prometheus/blackbox_exporter/issues/646
> Change DoT default port to 853

- prober/dns.go
- prober/dns_test.go
- prober/http_test.go
- prober/utils_test.go
This follows the same pattern as probe_http_duration_seconds and
probe_icmp_duration_seconds: it captures the time it takes to perform
the actual request, excluding the time it takes to set up things.
probe_duration_seconds includes the time to perform the request as well
as all the time it takes to set it up. probe_dns_lookup_time_seconds
refers to the time it takes to resolve the target's address, so it
doesn't capture the time it takes to make one request for that target.
> Expose probe_dns_duration_seconds metric

- README.md
Since #509 (4bf18924d4645453ec3e240d01842b7f15db537c) the default timeout was changed to 2m. This change updates the README to reflect it.
> Update default timeout in README

- prober/http.go
- prober/tcp.go
- prober/tcp_test.go
- prober/tls.go
this change adds a new metric `probe_ssl_fingerprint_info` to both tcp
and http probes. the metric always returns 1 similar to the tls version
metric and contains the leaf certificates sha256 fingerprint (hex) as a
label value.
this change allows users to validate in prometheus if a particular
certificate is being served.
> prober/tls: adding metric to expose certificate fingerprint info

- prober/tcp_test.go
- prober/tls.go
Apologies if I've misunderstood the purpose of this metric but I believe that it should be reporting the earliest expiry date of the chain that expires last out of all the verified chains. Presently it's reporting the earliest expiry of the chain that expires first.
This wasn't identified by the test for this metric because the test is using an expired root certificate which is not included in the `VerifiedChains`, so there was only one chain for the method to iterate over and therefore `getLastChainExpiry` returned the same regardless of the logic.
> prober/tls: fix probe_ssl_last_chain_expiry_timestamp_seconds

- prober/icmp.go
A recent change modified the way an IPv4 raw socket is created and BBE
is panicing when ICMPv4 is used with DontFragment set.
golang.org/x/net doesn't seem to have a way to create the necessary
socket, so fall back to the previous method for that case in particular
(ICMP, IPv4, DontFragment=true).
Fixes #685
> Fix panic when running ICMPv4 probe with DontFragment

- prober/http.go
- prober/http_test.go
Without regexp validations, the current code reads the response from the
server in order to figure out the number of bytes we received. With
regular expression validations, it's necessary to read the whole
response in order verify it if matches or not. In this case, since the
response is completely consumed, the current code is reporting a length
of 0.
Modify the code so that we can keep track of the content length in
either case: wrap the io.ReadCloser that corresponds to the response
body with another io.ReadCloser that keeps track of the number of bytes
read. After completely consuming the reponse, the wrapper is able to
report the total number of bytes read.
Add TestContentLength that checks the content lenght is reported
correctly. This includes checking cases with content encoding …
> Fix issue #673: incorrect content length reporting

- prober/http.go
> Log http version string we compare with, rather than float we put in metric.

- prober/icmp.go
IPv4 TTL (IPv6 hoplimit) identifies the number of routers used by
an arriving packet. It can be used to detect routing problems.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
> Add probe_icmp_reply_ttl_total

- prober/http.go
Not sure if that can be triggered in real scenarios.
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> http prober: Fix error checking

- prober/utils.go
- prober/utils_test.go
Prior to this change, LookupIPAddr() is used to do the DNS query,
which sends two DNS queries for A/AAAA records, even if the config has
preferred protocol set to ip4 and does not allow fallback protocol.
This change will change to use LookupIP() with the preferred protocol,
and only try fallback protocol if it's set to true. In most cases doing
this will save one RTT of DNS query.
Fixes #724
> Use preferred protocol first when resolving hostname

- Makefile.common
- prober/http.go
- prober/http_test.go
- prober/utils_test.go
Newer versions of golangci-lint flag a possible nil pointer dereference,
so rework some of the logic to make sure that's not the case.
Closes #738
> Update golangci-lint to 1.36.0

- main.go
The existing endpoints expose potentially sensitive data. So they cannot be used without authentication to check from the internet if the services is running.
> Add health endpoint

- prober/http.go
I have issue with some _tls_ phase with the http probe. It appears it is caused by the way it's calculated (`trace.gotConn - trace.dnsDone` ) which isn't always reliable.
This proposed fix uses `TLSHandshakeStart` and `TLSHandshakeDone` hooks.
> http probe - fix how the tls phase is calculated

- CONFIGURATION.md
- config/config.go
- config/config_test.go
- config/testdata/invalid-http-compression-mismatch.yml
- config/testdata/invalid-http-request-compression-reject-all-encodings.yml
- example.yml
- go.mod
- go.sum
- prober/http.go
- prober/http_test.go
If the module configuration specifies the "compression" option
blackbox_exporter will try to decompress the response using the
specified algorithm. If the response is not compressed using that
algorithm, the probe will fail.
It validates that the "Accept-Encoding" header is either absent, or that
it specifies the same algorithm as the "compression" option. If the
"Accept-Encoding" header is present but it specifies a different
algorithm, the probe will fail.
If the compression option is *not* used, probe_http_content_length and
probe_http_uncompressed_body_length will have the same value
corresponding to the original content length. If the compression option
is used and the content can be decompressed, probe_http_content_length
will report the original content length as it currently does, …
> Add support for decompression of HTTP responses

- blackbox.yml
This is to reduce log spam:
"sshd[3750]: Did not receive identification string from ..:"
There will still be a "Connection closed by" message.
> Fix example ssh_banner check: Send identification string

- README.md
- main.go
- main_test.go
- prober/http.go
This is refactoring of https://github.com/prometheus/blackbox_exporter/pull/816
As per [the design doc](https://docs.google.com/document/d/1VwqXi2TOb5KXaZY6Iio7411x64pJao3GusX8MqYsJ2g), the exporter now accept `hostname` parameter, which sets `Host` header for HTTP probes. It also sets TLS server name (if it is not already defined by module configuration) to avoid TLS handshake problems when `target` is an IP address. Setting `Host` with both module configuration and `hostname` parameter results in 400 Bad Request.
> Add hostname parameter

- prober/http.go
Hello.
According to prometheus scrape behavior [here](https://github.com/prometheus/prometheus/blob/48d25e6fe7d960c76c01763303c38f11168b1bba/scrape/scrape.go#L520) Change default go http client user-agent
from "Go-http-client/1.1" to "BlackBox Exporter/{{ version }}"
Issue : https://github.com/prometheus/blackbox_exporter/issues/555
Maintainers : @brian-brazil
> Change default user agent

- CONFIGURATION.md
- config/config.go
- prober/dns.go
- prober/dns_test.go
- prober/utils_test.go
This defaults recursion desired to on to preserve existing behaviour,
but allows it to be configured.
Asked for in a comment in #474 and generally useful.
Signed-off-by: David Leadbeater <dgl@dgl.cx>
> Add control of recursion desired flag for DNS probes

- prober/utils.go
Select the correct slice of bytes to hash based on IPv4 or IPv6 address
family.
> Fix IP hash

- prober/http.go
Don't init http probe phase labels until we're ready to send the
request.
Avoids exposing 0 value samples for things we haven't started to
measure.
Fix http resolve timing to report lookup time even if it's an error
(ie not found).
Fixes: https://github.com/prometheus/blackbox_exporter/issues/579
> Delay init of http phase values

- CONFIGURATION.md
- README.md
Currenly gRPC is being supported by Blackbox exporter but not mentioned in the documentation. 
https://github.com/prometheus/blackbox_exporter/issues/893
> gRPC added to README and Configuration

- CONFIGURATION.md
Renamed according to this line.
https://github.com/prometheus/blackbox_exporter/blob/91372eba6cdef09f6d8453752cf47011bf32cb7a/config/config.go#L269
> Rename dns recursion flag to recursion_desired

- main.go
Setting a small timeout value in a scraper (Prometheus) without changing the default offset leads to negative timeout values.
Fixes #868
Signed-off-by: Kirill Zhdanov <kzhdanov@mirantis.com>
> Negative maxTimeoutSeconds

- prober/http.go
- prober/http_test.go
The cases.Caser returned by calling cases.Title *cannot* be shared among
goroutines. This might happen when Prometheus tries to scrape multiple
targets at the same time. From the docs:
A Caser may be stateful and should therefore not be shared between
goroutines.
Fixes: #922
> Make caser a local varialbe, not a global one.

- main.go
Following the change in
https://github.com/prometheus/prometheus/pull/8542 blackbox_exporter
will send all usage out to stdout, not stderr.
Fixes: #912
> Print to stdout, not stderr

- CONFIGURATION.md
- config/config.go
- prober/http.go
- prober/http_test.go
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
> HTTP: Add Skip Resolve Phase With Proxy option

- example.yml
updating example module config to include proxy_url and skip_resolve_phase_with_proxy
related to issue #877
> add example to skip dns resolve and using proxy

- prober/grpc_test.go
- prober/http.go
- prober/http_test.go
- prober/tcp_test.go
`ioutil` is deprecated from go1.16 (ref: https://go.dev/doc/go1.16#ioutil).
So removed them.
Signed-off-by: inosato <si17_21@yahoo.co.jp>
> Remove ioutil

- config/config.go
- go.mod
- prober/handler.go
- prober/http.go
- prober/http_test.go
Using the full i18n library isn't needed, this just needs to be ASCII per MIME style header standards.
Signed-off-by: David Leadbeater <dgl@dgl.cx>
> Use textproto.CanonicalMIMEHeaderKey

- prober/grpc.go
- prober/http.go
- prober/prober.go
- prober/tcp.go
Move prober metric GaugeOpts into prober.go to reduce copy-n-paste.
> Refactor prober gauges

- prober/tcp.go
I noticed the probe_tls_version_info and probe_ssl_last_chain_info metrics were missing from STARTTLS TCP probes and added them.
Signed-off-by: Lyas Spiehler <lspiehler@gmail.com>
> Add missing probe_tls_version_info and probe_ssl_last_chain_info metrics to STARTTLS TCP probes

- README.md
* Remove `-d` so it's easier to see errors interactively.
* Use `latest` tag to make sure users use the release by default.
> Update Docker run docs

- go.mod
- go.sum
github.com/prometheus/exporter-toolkit has a new release v0.7.2 with fix for CVE-2022-46146, see [advisory for more details](https://github.com/prometheus/exporter-toolkit/security/advisories/GHSA-7rg2-cxvp-9p7p)
> Update prometheus/exporter-toolkit to v0.7.2

- prober/dns.go
- prober/dns_test.go
Currently, one may not be able to differentiate between a query refusal
by the target and the target not responding to a query. These two cases
can have very different ramifications.
This patch adds the probe_dns_query_succeeded gauge which is 1 if and
only if the DNS query was executed correctly, i.e., that the target
host has sent a response, and 0 otherwise.
Resolves #474
Signed-off-by: Daniel Teunis <daniel@teunis.cc>
> Add probe_dns_query_succeeded metric

- CONFIGURATION.md
The Exporter configuration is complicated by the omission of the root (`modules`) key from the configuration document.
Not only must configuration begin with `modules` but each module is a map of module names to module values.
I think I've correctly reflected this here using the document's schema.
Signed-off-by: Daz Wilkin <DazWilkin@users.noreply.github.com>
> Add root (`modules`) key to CONFIGURATION.md

- example.yml
From [changelog](https://github.com/prometheus/blackbox_exporter/blob/master/CHANGELOG.md):
> Fix example.yml: no_follow_redirects is deprecated in favor of follow_redirects

- CONFIGURATION.md
- config/config.go
- config/config_test.go
- config/testdata/invalid-http-body-config.yml
- example.yml
- prober/http.go
- prober/http_test.go
> Add support for HTTP request body as file

- config/config.go
- prober/handler.go
When blackbox exporter is imported as package (i.e in Grafana Agent) is exporting metrics event if the exporter is not enabled (see https://github.com/grafana/agent/issues/2627).
This PR moves the initialization of some of the internal metrics of the exporter out of `init` functions.
> Remove initialization of metrics from init functions

- config/config.go
- config/config_test.go
- main.go
- prober/handler.go
- prober/handler_test.go
- The first attempt to de-register internal metrics in #1056 was not sucessful.
- Added a `NewSafeConfig` function that gets a `prometheus.Registerer` as parameter and register config reloading metrics.
- Moved `moduleUnknownCounter` again to main and now it's passed (optionally) to `Handler` function.
> Explicit registration of internal exporter metrics

- main.go
- prober/history.go
- prober/history_test.go
Resolves #1062  
Adds funcionallity to allow search Probe logs based on the target allowing to build a direct link in Prometheus/Alertmanager Alerts
> feat: Allow to get Probe logs by target

- main.go
- prober/handler.go
- prober/handler_test.go
- prober/icmp.go
This PR adds a flag `--log.prober` which can be one of: [debug, info, warn, error, none] to investigate probe failures port-mortem. this flag defaults to none.
At the moment, this analyse problems is only possible via Web UI with an large enough history. Access the unprotected web ui can be difficult and the probe history is only available until restart.
> Log errors from probe

- CONFIGURATION.md
This is useful for checking for insecure TLS versions, see #1121
> document tls max_version option

- .circleci/config.yml
- .promu.yml
- README.md
- go.mod
* Update Go to 1.21.
* Update minimum Go version to 1.20.
* Remove obsolete extra build flgas.
Fixes: https://github.com/prometheus/blackbox_exporter/issues/1005
> Update Go build

- go.mod
- go.sum
- main.go
Use new client_golang version collector package. Replaces deprecated common version collector.
> Update version collector

- prober/http.go
- prober/prober.go
- prober/tls.go
Record name of ciphersuite negotiated during handshake in new `probe_tls_cipher_info` metric, useful for evaluating ciphers in use by monitored endpoints.
Example:
```shell
$ curl http://localhost:9115/probe?target=https://google.com&module=http_2xx
<...abbreviated...>
probe_tls_cipher_info{cipher="TLS_AES_128_GCM_SHA256"} 1
probe_tls_version_info{version="TLS 1.3"} 1
```
> add metric to record tls ciphersuite negotiated during handshake

- .golangci.yml
- config/config.go
- prober/http_test.go
- prober/tcp_test.go
* enable misspell linter 
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> Enable misspell linter

- prober/http_test.go
- prober/tcp_test.go
* Remove `t.Fatalf()` for non-printf strings.
* Remove unecessary `fmt.Sprintf()` inside `t.Fatalf()`.
> Fixup t.Fatalf() use

- CONFIGURATION.md
- blackbox.yml
- config/config.go
- prober/tcp.go
- prober/tcp_test.go
I wanted to create an exporter to check if all my hosts had an updated `sshd` (due to recent CVEs) then I resorted to using blackbock exporter by matching the "fixed" version and the timeout:
```yaml
ssh_freebsd_secure:
prober: tcp
timeout: 5s
tcp:
query_response:
- expect: "^SSH-2.0-OpenSSH_[0-9.]+ FreeBSD-20240806$"
```
but then again I'd prefer to capture the value as a label and do my checks by coloring the value in Grafana table later on or in alertmanager rules so I did this change instead.
I tried to do it in a generic way so that it can be used also for very different cases when matching part of the protocol chat is useful.
This produces scraping values like these:
```
probe_content{ssh_comments="FreeBSD-20240806",ssh_version="OpenSSH_9.7"} 1
```
BTW: I know no Go, except a …
> Add a way to export labels with content matched by the probe

- CONFIGURATION.md
The valid_status_codes expects a list between square brackets. Without you get this error: cannot unmarshal !!str \`200, 401\` into []int
> Update CONFIGURATION.md to clarify that valid_status_codes expects a list

- prober/grpc_test.go
These tests have been failing on the `test` pipeline CI for a while, but they run fine locally on the systems that support ipv4 and ipv6
Since we have `test-ipv6` pipeline that runs full test suite in a docker image with IPv6 enabled,
we should be okay to skip these Tests on the `test` pipeline.
The reason these tests are failing is because they are using `net.Listen("tcp", "localhost:0")`,
the use of `tcp` network expects both IPv4 and IPv6.
If we don't want to skip these tests, we can split these tests into a table test with `tcp4` and `tcp6`, and only skip `tcp6` on the `test` pipeline.
this was the first approach that came to my mind, and I am open to other approaches as well. if you can think of something better, please suggest other approaches as well.
> Skip failing IPv6 tests in test CI Pipeline

- example.yml
Adding the RabbitMQ probe example shared by @victorpablosceruelo in https://github.com/prometheus/blackbox_exporter/issues/1074
thanks @victorpablosceruelo for the RabbitMQ probe config example.
Fixed https://github.com/prometheus/blackbox_exporter/issues/1074
> Add RabbitMQ probe example

- CONFIGURATION.md
- config/config.go
- config/config_test.go
- example.yml
- go.mod
- go.sum
- prober/http.go
- prober/http_test.go
This PR implements parsing a JSON response from the body and checking the result using a CEL query. Looking for feedback on this.
Sample usage:
```
modules:
http_2xx:
prober: http
http:
fail_if_body_json_not_matches_cel: "body.foo.bar == 'baz'"
```
If response is `{"foo": { "bar": "qux" } }` the probe fails. fail_if_body_json_matches_cel is also implemented and should work as expected.
> Support matching JSON body with CEL expressions

- prober/handler.go
Fixes issue reported here:
https://github.com/prometheus/blackbox_exporter/pull/1381#issuecomment-3044749631
In aligning behavior for how the `--log.prober` flag is currently
expected to work, I didn't test it's effect on logs when used with the
`debug` URL parameter, as is often done for testing.
This changes the handler to always write to the internal buffer logger
(which is what is used to store the logs for displaying with the `debug`
url param), and it only writes through to the real logger if it's
enabled for the level the prober is set to. This ensures that logs are
always available with the `debug` param, while still correctly filtering
levels for console output at stderr.
As a consequence of thinking about how to make this work, I also
realized it wasn't necessary to manually …
> fix: make `debug` param log output work regardless of log level
