prometheus/blackbox_exporter

- Makefile
- Makefile.COMMON
Now will match other prometheus projects.
> Switch to go version 1.5.1.

- README.md
- blackbox.yml
- http.go
- main.go
- tcp.go
- tls.go
Also, report certificate expiration date just like HTTPS probe does.
> Support TLS in TCP connections

- README.md
- http.go
- http_test.go
- main.go
Allow InsecureSkipVerify for self-signed certificates (Issue  #41)
> http: implement TLS and InsecureSkipVerify

- README.md
- http.go
- main.go
Supersedes https://github.com/prometheus/blackbox_exporter/pull/55
> Added support for posting a body of content

- main.go
> Fix trivial tyop in main.go

- .travis.yml
- Makefile
- http.go
And 	ensure CI will fail on unformatted code next time.
@brian-brazil
> Fix code formatting

- Makefile
- dns.go
- dns_test.go
- http.go
- icmp.go
- main.go
- tcp.go
- tcp_test.go
> Fix go linter issues and simplify code

- dns.go
- http.go
- icmp.go
- tcp.go
> Use warn level for log messages about target communication errors

- main.go
Associate with #135 , we need a reloadable mechanism.
> Implement reloadable config

- README.md
- dns.go
- dns_test.go
- http.go
- http_test.go
- icmp.go
- main.go
- tcp.go
- tcp_test.go
- utils.go
- utils_test.go
Utility methods for probes for #154
> Probe utility methods

- tcp.go
> Log tcp errors

- config.go
- config_test.go
- main.go
- testdata/blackbox-good.yml
/config now reveals loaded Blackbox exporter configuration in YAML format.
> Added expose loaded blackbox configuration on /config

- http.go
- http_test.go
- tcp.go
- tcp_test.go
- utils_test.go
> Added metric for http/tcp regex match

- blackbox.yml
- circle.yml
- main.go
> Handle timeout header being missing

- tcp.go
- tcp_test.go
> Fixed timeout bug

- CONFIGURATION.md
> Fix docs http valid_status_codes type

- history.go
- main.go
- main_test.go
> Add last 100 probes to the front page, with logs

- history.go
- main.go
> Fix memory leak in result history

- config/config.go
- config/config_test.go
- config/testdata/blackbox-bad2.yml
- vendor/github.com/prometheus/common/config/http_config.go
- vendor/vendor.json
> Fix missing validation of HTTP client configuration

- example.yml
Just a small addition to example configuration. I had to find that one searching issues.
> Add example with custom CA

- .circleci/config.yml
Similar to https://github.com/prometheus/prometheus/pull/4182
> Fix CircleCI for releases

- .circleci/config.yml
Signed-off-by: Ben Kochie <superq@gmail.com>
> Update CircleCI to Go 1.11

- vendor/github.com/prometheus/client_golang/prometheus/collector.go
- vendor/github.com/prometheus/client_golang/prometheus/counter.go
- vendor/github.com/prometheus/client_golang/prometheus/desc.go
- vendor/github.com/prometheus/client_golang/prometheus/doc.go
- vendor/github.com/prometheus/client_golang/prometheus/fnv.go
- vendor/github.com/prometheus/client_golang/prometheus/gauge.go
- vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/histogram.go
- vendor/github.com/prometheus/client_golang/prometheus/http.go
- vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
- vendor/github.com/prometheus/client_golang/prometheus/labels.go
- vendor/github.com/prometheus/client_golang/prometheus/metric.go
- vendor/github.com/prometheus/client_golang/prometheus/observer.go
- vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/github.com/prometheus/client_golang/prometheus/registry.go
- vendor/github.com/prometheus/client_golang/prometheus/summary.go
- vendor/github.com/prometheus/client_golang/prometheus/value.go
- vendor/github.com/prometheus/client_golang/prometheus/vec.go
- vendor/github.com/prometheus/client_golang/prometheus/wrap.go
- vendor/vendor.json
Signed-off-by: Ben Kochie <superq@gmail.com>
> Update vendor github.com/prometheus/client_golang/...@v0.9.0

- main.go
https://github.com/prometheus/prometheus/pull/4865
@simonpasquier
> Signal channel should have a buffer of 1.

- config/config.go
- prober/http_test.go
- prober/tcp_test.go
- prober/utils.go
Fix bug https://github.com/prometheus/blackbox_exporter/issues/424
and fix an undefined probeIPProtocolGauge in case of no IP found.
Signed-off-by: Pascal Gauthier <pgauthier@nihilisme.ca>
> Fix ip_protocol_fallback default value 

- Dockerfile
low hanging fruit
Signed-off-by: silentpete <peter.gallerani@gmail.com>
> #352 - swap MAINTAINER for LABEL

- go.mod
- go.sum
- prober/http.go
- vendor/github.com/alecthomas/template/go.mod
- vendor/github.com/alecthomas/units/go.mod
- vendor/modules.txt
> Don't put v4 addresses in brackets

- .circleci/config.yml
- .promu.yml
- .travis.yml
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Update to go 1.15

- main.go
> Correct formatting of build_context log message at startup

- config/testdata/blackbox-good.yml
- example.yml
related to #703 
Signed-off-by: Björn Fischer <bjoern.fischer@inovex.de>
> make smtp examples compliant to spec

- .github/ISSUE_TEMPLATE.md
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>
> Fix version flag in github template

- MAINTAINERS.md
@mem and @electron0zero: please verify that I have used your preferred email address for this purpose. And please approve, if you agree with your nomination. (I cannot mark you as a reviewer yet, but this will change once this is merged and we add you to the org.)
> Change maintainer from @brian-brazil to @roidelapluie, @mem, @electron0zero

- prober/utils.go
- prober/utils_test.go
This change is an attempt to fix #791
> Simplify prefered protocol DNS probe

- README.md
it helps getting the grasp of the purpose of the relabel_config.
> add a link to guide "multi-target exporter pattern"

- go.mod
- go.sum
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
> Use BBE user agent for oauth2

- CONFIGURATION.md
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>
> Make Proxy Connect Headers consistent with Prometheus

- CONFIGURATION.md
Fix incorrect parameters name in documentation
> Modify document [issue 1109]
